services:
  bittorrent-cli:
    build: 
      context: ../
      dockerfile: ./Dockerfile
    command: --interactive=false --torrent=./torrent/torrent.torrent --download=./data
    volumes:
      - ./torrent:/torrent
    networks:
      swarm:
        ipv4_address: 10.5.0.127
    logging:
      driver: "json-file"
      options:
        max-size: "32m"

networks:
  swarm:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1