services:
  bittorrent-cli:
    build:
      context: ../
      dockerfile: ./Dockerfile
    command: --interactive=false --torrent=./torrent/torrent.torrent --download=./data
    volumes:
      - ./torrent:/torrent
    networks:
      swarm:
        ipv4_address: 10.5.0.100
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
    depends_on:
      tracker:
        condition: service_healthy

  seed:
    build:
      context: ./
      dockerfile: ./transmission-cli-seed.Dockerfile
    networks:
      swarm:
        ipv4_address: 10.5.0.200
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
    depends_on:
      tracker:
        condition: service_healthy

  tracker:
    image: jarylc/bittorrent-tracker
    environment:
      - PORT=8000
      - HTTP=1
      - UDP=0
      - WS=0
      - INTERVAL=10000
    networks:
      swarm:
        ipv4_address: 10.5.0.250
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider tracker:8000/stats || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  swarm:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
